App\Core\Domain\Model\User:
  xml_root_name: user
  read_only: false
  relations:
    - rel: self
      href: expr('/api/user/' ~ object.id()) ]
  properties:
    id:
      xml_attribute: true
      type: int
      groups: [ default ]
    email:
      type: string
      groups: [ default ]
    name:
      type: string
      groups: [ default ]
    roles:
      type: array
      groups: [ default ]
    password:
      exclude_if: context.getDirection() === 1
    emailVerified:
      type: bool
      read_only: true
    active:
      type: bool
      read_only: true


