app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

action_controllers:
    resource: ../src/Core/Infrastructure/Controller/Auth/
    type: annotation
    prefix: /auth

resource_controllers:
    resource: ../src/Core/Infrastructure/Controller/Api/
    type: annotation
    prefix: /api

kernel:
    resource: ../src/Kernel.php
    type: annotation
